# fly.toml app configuration file generated for mars-workflow-analytics-v2-restless-frog-7414 on 2025-01-07T11:40:25-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mars-workflow-analytics-v2-restless-frog-7414'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'mars_workflow_analytics_data'
  destination = '/data'
  

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_count = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 4
  memory_mb = 8192
  count = 1

[env]
  SUPABASE_URL = "https://rlstohtqonbhrcwrdcru.supabase.co"
  FRAMES_DIR = "/data"
